#!/bin/bash

cd `dirname $0`

. my-funcs

SYSNAME=$(uname -s)
if check-cmd lsb_release; then
    DIST=$(lsb_release -i -s)
elif [ -r /etc/redhat-release ]; then
    DIST=$(cat /etc/redhat-release | awk '{print $1}')
fi
# install software packages
if [ "$SYSNAME" = Linux -a "$DIST" = Ubuntu ]; then
    sudo sed -i.bak -r -e "s%https?://(.*)(archive.ubuntu.com|mirrors.edge.kernel.org)/ubuntu%http://ftp.iij.ad.jp/pub/linux/ubuntu/archive%g" /etc/apt/sources.list
    sudo -E apt update && sudo -E apt upgrade -y && sudo -E apt autoremove -y
    sudo -E apt install -y vim tmux sysstat curl
elif [ "$SYSNAME" = Linux -a "$DIST" = Debian ]; then
    sudo -E apt update && sudo -E apt upgrade -y && sudo -E apt autoremove -y
    sudo -E apt install -y vim tmux sysstat curl
elif [ "$SYSNAME" = Linux -a "$DIST" = CentOS ]; then
    sudo -E yum update -y
    sudo -E yum install -y vim-enhanced tmux sysstat curl
fi

# git configuration
git config --global core.editor vim
git config --global user.name zeroichi
git config --global user.email 'zeroichi@users.noreply.github.com'

# injection into .bashrc
add-code ~/.bashrc "# zeroichi's customization #" <<EOS
if [ -f $PWD/bashrc ]; then
    . $PWD/bashrc
fi
EOS

# injection into .profile
# note: bash looks for .bash_profile, .bash_login, and .profile, in that order
PROFILE_FILE=~/.profile
if [ -r ~/.bash_login ]; then
    PROFILE_FILE=~/.bash_login
fi
if [ -r ~/.bash_profile ]; then
    PROFILE_FILE=~/.bash_profile
fi
add-code $PROFILE_FILE "# zeroichi's customization #" <<EOS
if [ -f $PWD/bash_profile ]; then
    . $PWD/bash_profile
fi
EOS

# install .vimrc
if [ ! -e ~/.vimrc ]; then
    ln -s $PWD/vimrc ~/.vimrc
    echo .vimrc has been installed.
fi

# install .tmux.conf
if [ ! -e ~/.tmux.conf ]; then
    ln -s $PWD/tmux.conf ~/.tmux.conf
    echo .tmux.conf has been installed.
fi
