#!/bin/bash

cd `dirname $0`

. my-funcs

add-code ~/.bashrc "# zeroichi's customization #" <<EOS
if [ -f $PWD/bashrc ]; then
	. $PWD/bashrc
fi
EOS

PROFILE_FILE=~/.bash_profile
if [ -f ~/.profile ]; then
	PROFILE_FILE=~/.profile
fi
add-code $PROFILE_FILE "# zeroichi's customization #" <<EOS
if [ -f $PWD/bash_profile ]; then
	. $PWD/bash_profile
fi
EOS

if [ ! -e ~/.vimrc ]; then
	ln -s $PWD/vimrc ~/.vimrc
fi

if [ ! -e ~/.tmux.conf ]; then
	ln -s $PWD/tmux.conf ~/.tmux.conf
fi
